example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_xml 
from mywatchlist.views import show_json
from mywatchlist.views import show_json_id 
from mywatchlist.views import show_xml_id 

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_id, name='show_json_id'),
    path('xml/<int:id>', show_xml_id, name='show_xml_id'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import  add_task, delete_task, register,  show_todolist, show_todolist_json, update_task
from todolist.views import login_user
from todolist.views import logout_user  
from todolist.views import new_task



app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', new_task, name='new_task'),
     path('delete/<int:id>', delete_task, name="delete_task"),
    path('update/<int:id>', update_task, name="update_task"),
    path('json/', show_todolist_json, name="show_todolist_json"),
    path('add/', add_task, name="add_task"),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

# Create your models here.
class WatchList(models.Model):
    watched = models.BooleanField(max_length=50)
    title = models.TextField()
    rating = models.IntegerField()
    release_date = models.TextField()
    review = models.TextField()

todolist/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=150)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_katalog(request):
    return render(request, "katalog.html", context)

data_katalog_item = CatalogItem.objects.all()
context = {
    'list_item' : data_katalog_item,
    'name': 'Muhammad Fiqo Anugrah',
    'NPM' : '2106657286'
}

mywatchlist/views.py
from django.shortcuts import render
from multiprocessing import context
from operator import truediv
from django.shortcuts import render
from mywatchlist.models import WatchList
from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_mywatchlist(request):
    mywatchlist_data = WatchList.objects.all()

    watched_number = 0
    unwatched_number = 0
    message = ""

    for x in mywatchlist_data:
        if x.watched == True:
            watched_number+=1
        else :
            unwatched_number+=1
    if watched_number >= unwatched_number :
        message = ("Congratulations, you have watched a lot of movies!")
    else :
        message = ("Woah, you need to watch more movies!")

    context = {
        'mywatchlist_list': mywatchlist_data,
        'nama': 'Muhammad Fiqo Anugrah',
        'id': '2106657286',
        'message': message
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data_xml = WatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data_xml), content_type="application/xml")

def show_json(request):
    data_json = WatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data_json), content_type="application/json")

def show_json_id(request, id):
    data_json_id = WatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data_json_id), content_type="application/json")

def show_xml_id(request, id):
    data_xml_id = WatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data_xml_id), content_type="application/xml")

todolist/views.py
import datetime
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.shortcuts import render
from todolist.models import Task
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.core import serializers

# TODO: Create your views here.
@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_todolist_item = Task.objects.filter(user=request.user)
    context = {"list_item": data_todolist_item, "username": request.user}
    
    return render(request, 'todolist.html',context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created!')
            return redirect('todolist:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # create response
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def new_task(request):
    if request.method == 'POST':
        response = HttpResponseRedirect(reverse('todolist:show_todolist'))
        Task.objects.create(user = request.user,date = datetime.datetime.now(),title = request.POST.get('title'),description = request.POST.get('description'),)
        return response
    context = {}
    return render(request, 'new_task.html',context)

def update_task(request, id):
    task = Task.objects.get(pk=id)
    if task.is_finished:
        task.is_finished = False
    else:
        task.is_finished = True
    task.save()
    return HttpResponseRedirect("/todolist/")

def delete_task(request, id):
    task = Task.objects.get(pk=id)
    task.delete()
    return HttpResponseRedirect("/todolist/")


# Assignment 6
@login_required(login_url="/todolist/login")
def show_todolist_json(request):
    tasks = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', tasks), content_type='application/json')

def add_task(request):
    if request.method == "POST":
        title = request.POST.get('title')
        description = request.POST.get('description')
        new_task = Task(user=request.user, title=title, description=description, date=datetime.now())
        new_task.save()
    return HttpResponse('')

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

{% block content %}

<h1>Lab 1 Assignment PBP/PBD</h1>

<h5>Name: </h5>
<b>{{name}}</b>

<h5>Student ID: </h5>
<b>{{NPM}}</b>

<div class="limiter">
  <div class="container-table100">
  <div class="wrap-table100">
  <div class="table100">
<table> 
<thead>
  <tr>
    <th>Item Name</th>
    <th>Item Price</th>
    <th>Item Stock</th>
    <th>Rating</th>
    <th>Description</th>
    <th>Item URL</th>
  </tr>
</thead>

  {% comment %} Add the data below this line {% endcomment %}
  {% for item in list_item %}
    <tr>
        <th>{{item.item_name}}</th>
        <th>{{item.item_price}}</th>
        <th>{{item.item_stock}}</th>
        <th>{{item.rating}}</th>
        <th>{{item.description}}</th>
        <th>{{item.item_url}}</th>
    </tr>
  {% endfor %}
  </table>

{% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

{% block content %}

  <h1> Assignment-3 PBD </h1>

  <h5>Name: </h5>
  <b>{{nama}}</b>

  <h5>Student ID: </h5>
  <b>{{id}}</b>

  <h5>Message: </h5>
  <b>{{message}}</b>

  <table border = "1" bordercolor = "gray">
    <tr>
      <th>Watched</th>
      <th>Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for mywatchlist in mywatchlist_list %}
    <tr>
        <th>{{mywatchlist.watched}}</th>
        <th>{{mywatchlist.title}}</th>
        <th>{{mywatchlist.rating}}</th>
        <th>{{mywatchlist.release_date}}</th>
        <th>{{mywatchlist.review}}</th>
    </tr>
    {% endfor %}
</table>

{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<!-- <body class="h-screen flex flex-col justify-center items-center bg-gradient-to-tr from-blue-500 to-red-500"> -->
  <body class="h-screen flex flex-col justify-center items-center">
    {% block content %}
    {% endblock content %}
  </body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

</html>

todolist/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<link rel="stylesheet" href="{% static 'login.css' %}" />

<audio autoplay loop src="Music/GenderangUniversitasIndonesia.mp3"></audio>

<div class="login">

    <form method="POST">
        {% csrf_token %}

        <body
            style="background-image: url(https://upload.wikimedia.org/wikipedia/id/thumb/0/0f/Makara_of_Universitas_Indonesia.svg/1200px-Makara_of_Universitas_Indonesia.svg.png);">
        </body>
        <div class="container">
            <div class="brand-logo"></div>
            <div class="brand-title">LOGIN</div>
            <div class="inputs">

                <div class="form">
                    <label>USERNAME</label>
                    <input type="text" name="username" placeholder="Username" />
                    <label>PASSWORD</label>
                    <input type="password" name="password" placeholder="Password" />
                    <button class="submit" type="text">LOGIN</button>
                    <a href="{% url 'todolist:register' %}">Create Account</a>
                    {% if messages %}

                    <ul>
                        {% for message in messages %}
                        <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                </div>
            </div>
    </form>
</div>
</div>

{% endblock content %}

todolist/templates/new_task.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Create New Task</title>
{% endblock meta %}

<link rel="stylesheet" href="{% static 'new_task.css' %}" />

{% block content %}

<div class="login">

    <form method="POST">
        {% csrf_token %}

        <body
            style="background-image: url(https://upload.wikimedia.org/wikipedia/id/thumb/0/0f/Makara_of_Universitas_Indonesia.svg/1200px-Makara_of_Universitas_Indonesia.svg.png);">
        </body>
        <div class="container">
            <div class="brand-logo"></div>
            <div class="brand-title">Create New Task</div>
            <div class="inputs">

                <div class="form">
                    <label>Task Title:</label>
                    <input type="text" name="title" placeholder="Enter Task Title" class="form-control">
                    <label>Task Description:</label>
                    <input type="text" name="description" placeholder="Enter Task Description" class="form-control">
                    <input type="submit" name="submit" value="Submit"/>
           
                </div>
            </div>
    </form>
</div>
</div>





{% endblock content %}


<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;900&display=swap');


input {
  caret-color: red;
}

body {
  margin: 0;
  width: 100vw;
  height: 100vh;
  background: #ecf0f3;
  display: flex;
  align-items: center;
  text-align: center;
  justify-content: center;
  place-items: center;
  overflow: hidden;
  font-family: poppins;
}

.container {
  position: relative;
  width: 350px;
  height: 500px;
  border-radius: 80px;
  padding: 40px;
  box-sizing: border-box;
  background: #ecf0f3;
  box-shadow: 14px 14px 20px #cbced1, -14px -14px 20px white;
}

/* .brand-logo {
  height: 100px;
  width: 100px;
  background: url("https://i.ytimg.com/vi/GM07SXU7lEo/maxresdefault.jpg");
  margin: auto;
  border-radius: 50%;
  box-sizing: border-box;
  box-shadow: 7px 7px 10px #cbced1, -7px -7px 10px white;
} */

.brand-title {
  margin-top: 10px;
  font-weight: 900;
  font-size: 1.8rem;
  color: #FBC801;
  letter-spacing: 1px;
}

.inputs {
  text-align: left;
  margin-top: 30px;
}

label, input, button {
  display: block;
  width: 100%;
  padding: 0;
  border: none;
  outline: none;
  box-sizing: border-box;
}

label {
  margin-bottom: 4px;
}

label:nth-of-type(2) {
  margin-top: 12px;
}

input::placeholder {
  color: gray;
}

input {
  background: #ecf0f3;
  padding: 10px;
  padding-left: 20px;
  height: 50px;
  font-size: 14px;
  border-radius: 50px;
  box-shadow: inset 6px 6px 6px #cbced1, inset -6px -6px 6px white;
}

button {
  color: rgb(0, 0, 0);
  margin-top: 20px;
  background: #FBC801;
  height: 40px;
  border-radius: 20px;
  cursor: pointer;
  font-weight: 900;
  box-shadow: 6px 6px 6px #cbced1, -6px -6px 6px white;
  transition: 0.5s;
}

button:hover {
  box-shadow: none;
}

a {
  position: absolute;
  font-size: 10px;
  bottom: 40px;
  right: 133px;
  text-decoration: none;
  color: black ;
  background: #FBC801;
  border-radius: 6px;
  padding: 2px;
}

h1 {
  top: 0;
  left: 0;
}

li{
    position: absolute;
    font-size: 10px;
    color: black;
    height: px;
}
</style>

todolist/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}

<link rel="stylesheet" href="{% static 'register.css' %}" />

<form method="POST">
    {% csrf_token %}

    <body
        style="background-image: url(https://upload.wikimedia.org/wikipedia/id/thumb/0/0f/Makara_of_Universitas_Indonesia.svg/1200px-Makara_of_Universitas_Indonesia.svg.png);">
    </body>
    <div class="container">
        <div class="brand-logo"></div>
        <div class="brand-title">REGISTRATION</div>
        <div class="inputs">

            {{ form.as_table }}

            <div class="login">
                <a href="{% url 'todolist:register' %}">Create Account</a>
            </div>
            <button><a href="{% url 'todolist:logout' %}">Sign In</a></button>
        </div>
        {% if messages %}
        <ul>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
</div>
</form>

{% endblock content %}

todolist/templates/registration.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Registration Form</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
            <button><a href="{% url 'todolist:logout_user' %}">Logout</a></button>
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
<!-- get data from /todolist/json -->
<script>
    $(document).ready(function () {
        $('.modal').hide();
        $('.backdrop').hide();
        $.get('/todolist/json/', function (data, status) {
            let content = '';
            for (let i = 0; i < data.length; i++) {
                let message = data[i].fields.is_finished ? 'Selesai' : 'Belum Selesai';
                let color = data[i].fields.is_finished ? 'blue' : 'red';
                content += `
          <div class="text-white hover:scale-105 duration-150 flex flex-row justify-between p-3 lg:w-[30rem] sm:w-[25rem] h-24 bg-zinc-800 box-shadow-md rounded-xl">
              <div>
              <h2 class="font-semibold lg:text-md sm:text-sm">${data[i].fields.title}</h2>
              <h3 class="lg:text-sm sm:text-xs text-gray-500">${data[i].fields.description}</h3>
              <p class="text-xs text-gray-500">created: ${data[i].fields.date}</p>
              <p class="text-xs font-semibold text-${color}-500">${message}</p>
            </div>
            <div class="flex flex-col text-sm lg:scale-100 sm:scale-60">
              <a href="update/${data[i].pk}"><button class="m-1 bg-blue-500 hover:bg-blue-700 hover:cursor-pointer h-7 w-20 rounded-md">Update</button></a>
              <a href="delete/${data[i].pk}"><button class="m-1 bg-red-500 hover:bg-red-700 hover:cursor-pointer h-7 w-20 rounded-md">Delete</button></a>
            </div>
          </div>
        `;
                $('.content').html(content);
            }
        })
    })
</script>
{% endblock meta %}


{% block content %}

<!-- header -->
<div class="absolute top-0 text-white p-5 h-14 flex flex-row justify-between items-center w-screen bg-slate-700">
    <h1 class="lg:text-2xl sm:text-xl font-bold">PBD Assignment</h1>
    <div class="flex flex-row items-center font-semibold lg:scale-100 sm:scale-75">
        <button class="add-task m-1 bg-green-500 hover:bg-green-700 hover:cursor-pointer px-4 py-2 rounded-lg">Add
            Task</button>
        <a href="{% url 'todolist:new_task' %}"><button
                class="m-1 bg-blue-500 hover:bg-blue-700 hover:cursor-pointer px-4 py-2 rounded-lg">New
                Task</button></a>
        <a href="{% url 'todolist:logout' %}"><button
                class="m-1 bg-red-500 hover:bg-red-700 hover:cursor-pointer px-4 py-2 rounded-lg">Logout</button></a>
    </div>
</div>

<h1 class="absolute top-16 mb-1 text-center text-xl font-semibold">Welcome to {{username}}'s To do list!</h1>

<!-- todolist contents -->
<div class="content absolute top-24 mb-3 grid grid-flow-cols lg:grid-cols-2 sm:grid-cols-1 gap-5 p-5 rounded-xl"></div>

<!-- backdrop modals -->
<div class="backdrop mt-14 h-[100vh] w-[100vw] bg-red-100 z-10 opacity-80"></div>

<!-- modals -->
<div
    class="modal absolute flex flex-col justify-center items-center z-20 w-[30rem] h-[20rem] bg-gray-100 outline-2 shadow-2xl rounded-xl hover:scale-105 duration-150">

    {% csrf_token %}
    <h1 class="text-2xl font-bold mb-4">ADD NEW TASK</h1>
    <div class="flex flex-col m-1">
        <label class="font-semibold">Judul</label>
        <input class="judul w-[17rem] p-2 rounded-lg border-[1px] border-black" placeholder="judul" required>
    </div>
    <div class="flex flex-col m-1">
        <label class="font-semibold">Deskripsi</label>
        <input class="deskripsi w-[17rem] p-2 rounded-lg border-[1px] border-black" placeholder="deskripsi" required>
    </div>
    <button
        class="add-task-button m-3 bg-green-500 hover:bg-green-700 hover:cursor-pointer px-6 py-2 rounded-lg">ADD</button>
</div>

</div>

<!-- click add task button -->
<script>
    $(document).ready(function () {
        $('.add-task').click(function () {
            $('.modal').toggle();
            $('.backdrop').toggle();
        })
    })
</script>

<!-- click add task button in modal -->
<script>
    $(document).ready(function () {
        $('.add-task-button').click(function () {
            let judul = $('.judul').val();
            let deskripsi = $('.deskripsi').val();
            let CSRFtoken = $('input[name="csrfmiddlewaretoken"]').val();
            $.post('/todolist/add/', {
                title: judul,
                description: deskripsi,
                csrfmiddlewaretoken: CSRFtoken
            }, function () {
                $('.modal').hide();
                $('.backdrop').hide();
                $.get('/todolist/json/', function (data, status) {
                    let content = '';
                    for (let i = 0; i < data.length; i++) {
                        let message = data[i].fields.is_finished ? 'Selesai' :
                            'Belum Selesai';
                        let color = data[i].fields.is_finished ? 'blue' : 'red';
                        content += `
                <div class="text-white hover:scale-105 duration-150 flex flex-row justify-between p-3 lg:w-[30rem] sm:w-[25rem] h-24 bg-zinc-800 box-shadow-md rounded-xl">
                    <div>
                    <h2 class="font-semibold lg:text-md sm:text-sm">${data[i].fields.title}</h2>
                    <h3 class="lg:text-sm sm:text-xs text-gray-500">${data[i].fields.description}</h3>
                    <p class="text-xs text-gray-500">created: ${data[i].fields.date}</p>
                    <p class="text-xs font-semibold text-${color}-500">${message}</p>
                  </div>
                  <div class="flex flex-col text-sm lg:scale-100 sm:scale-60">
                    <a href="update/${data[i].pk}"><button class="m-1 bg-blue-500 hover:bg-blue-700 hover:cursor-pointer h-7 w-20 rounded-md">Update</button></a>
                    <a href="delete/${data[i].pk}"><button class="m-1 bg-red-500 hover:bg-red-700 hover:cursor-pointer h-7 w-20 rounded-md">Delete</button></a>
                  </div>
                </div>
              `;
                        $('.content').html(content);
                    }
                })
            })
        })
    })
</script>

<!-- click modals backdrop -->
<script>
    $(document).ready(function () {
        $('.backdrop').click(function () {
            $('.modal').hide();
            $('.backdrop').hide();
        })
    })
</script>

{% endblock content %}